# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_explained', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Easy with no help'), (2, b'With a little help'), (3, b'With a lot help'), (4, b'Did not finnish')], null=True)),
                ('grade_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True, null=True)),
                ('test_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_testerja', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testiranec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_testiranca', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Male'), (2, b'Female')])),
                ('digital_maturity_level', models.PositiveIntegerField(choices=[(1, b'Use it every day'), (2, b'Sometimes use it'), (3, b'Use it only at work')])),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Tester'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_testiranec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Testiranec'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Test'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_tag',
            field=models.ManyToManyField(blank=True, to='Reports.Tag'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Task'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_testiranec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Testiranec'),
        ),
    ]
