# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part_name', models.CharField(max_length=200)),
                ('part_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_test',
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(default=b'SOME STRING'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.Product'),
        ),
    ]
