# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20160419_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(),
        ),
    ]
