# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_auto_20160419_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_product_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reports.Product_part'),
        ),
    ]
